image: Visual Studio 2017
configuration: Release
platform: x86
version: 2.0.{build}
clone_depth: 1
skip_tags: true

before_build:
  - nuget restore

build:
  verbosity: minimal

after_build:
  - 7z a MAS345_GUI-v%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\\windowswitcher.app\bin\Release\*.*

artifacts:
  - path: MAS345_GUI-v$(appveyor_build_version).zip

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: $(appveyor_build_version)
  assembly_file_version: $(appveyor_build_version)

deploy:
  release: v$(appveyor_build_version)
  description: v$(appveyor_build_version)
  provider: GitHub
  auth_token:
    secure: uG/EbklyR/JLrHlnpnBTnVFyY1o9i2A61ceZ2NjJMkFSQO+oORMADOx/+3AP1LkK
  artifact: /.*\.zip/
  draft: true
  on:
    branch: master
